
[dependencies.stm32f7]
repository = "https://github.com/STMicroelectronics/stm32f7xx_hal_driver.git"
tag = "v1.3.0"

[dependencies.cmsis_device_f7]
repository = "https://github.com/STMicroelectronics/cmsis_device_f7.git"
tag = "v1.2.8"

[dependencies.cmsis5]
repository = "https://github.com/ARM-software/CMSIS_5.git"
tag = "5.9.0"

[toolchains.linux_clang]
container = "renemoll/builder_clang"
additional_options.configuration = "-G Ninja"

[toolchains.stm32]
container = "renemoll/builder_arm_gcc"
# additional_options.configuration = "-G Ninja"
toolchain_file = "bob-cmake/toolchains/toolchain_cortex-m7_fpu_dp.cmake"

[targets.host]
toolchain = "linux_clang"

[targets.stm32f7]
toolchain = "stm32"
additional_options.configuration = "-DMCU=STM32F767xx"
